# Generated by Django 5.1.7 on 2025-11-24 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_control', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('modalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('carrera', models.CharField(max_length=100)),
                ('plan_estudios', models.CharField(max_length=100)),
                ('modulo_especialidad', models.CharField(max_length=50)),
                ('creditos_acumulados', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('situacion_vigencia', models.CharField(max_length=50)),
                ('periodo_ingreso', models.CharField(max_length=20)),
                ('periodos_convalidados', models.IntegerField(default=0)),
                ('periodo_actual', models.CharField(max_length=20)),
                ('clave_curp', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('colonia', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('cp', models.CharField(max_length=10)),
                ('telefono_domicilio', models.CharField(max_length=20)),
                ('telefono_celular', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('escuela_procedencia', models.CharField(max_length=200)),
                ('tutor', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=100)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('periodo', models.CharField(max_length=20)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='inicio.alumno')),
            ],
        ),
    ]
