# Generated by Django 5.1.7 on 2025-11-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_oferta_remove_alumno_carrera_remove_alumno_extension_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=50)),
                ('tutor_asignado', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
