# Generated by Django 5.1.7 on 2025-11-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='tutor_asignado',
        ),
        migrations.AddField(
            model_name='docente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
