# Generated by Django 5.1.7 on 2025-11-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioEstandar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(choices=[('Matemáticas', 'Matemáticas'), ('Español', 'Español'), ('Historia', 'Historia'), ('Ciencias', 'Ciencias'), ('Inglés', 'Inglés')], max_length=50)),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('salon', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
