# Generated by Django 5.1.7 on 2025-11-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_horarioestandar_delete_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
